version: "3"

services:
  bot:
    image: node
    restart: ${RESTART}
    ports:
      - ${BOT_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./bot:/var/bot
    working_dir: /var/bot
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB=${MONGO_DB}
      - MONGO_PORT=${MONGO_PORT}
      - BOT_TOKEN=${BOT_TOKEN}
    command: npm run start

  mongo:
    image: mongo
    restart: ${RESTART}
    volumes:
      - ./database:/data/db
    ports:
      - ${MONGO_PORT}:27017